### ISSUE TITLE
EdgeX DevOps: Docker image naming

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/cd-management#102]
👕 - Small
    Architect’s meeting topic to resolve the naming standard we want
    DevOps has implementation once decided
    Drop “go” suffix and “docker” prefix
    Non backward compatible change (time to do it now)
[US7543](https://rally1.rallydev.com/#/detail/userstory/459132372372?fdp=true): EdgeX DevOps: Docker image naming

**Comment by ernestojeda** [comment]
Based on architects meeting Nov 30th the decision is:

- Drop “docker” prefix
- Drop “go” and "c" suffix
