### ISSUE TITLE
LFX security team code scanning

### ISSUE THREAD

**Issue by hutchic** [edgexfoundry/cd-management#150]
Received via email:

Hey Colin,

Just wanted to ping you again regarding EdgeX Foundry LFX Security onboarding.  Do you or anyone from your team have access to install our GitHub Application into the https://github.com/edgexfoundry GitHub Organization? The user must have GitHub owner permissions to install bots. Here are the steps:

To install the LFX Security GitHub App:

1.      Click on the following link: https://github.com/apps/lfx-security-github-app/installations/new

2.      Review the list of organizations you belong to. Click on the GitHub Organization you wish to install the bot into (edgexfoundry organization in this case)

3.      On the "Install and Authorize LFx Security GitHub App" page, determine which repositories should have the GitHub App installed. We recommend all repositories, but the GitHub owner can choose a subset.

4.      Click on Install & Authorize to complete the installation.

Thanks,
David

LFX Security Technical Lead

**Comment by ernestojeda** [comment]
This would be something the LF would have to do. They own all the Edgexfoundry GitHub organizations. I would like to know more about what level of scanning this does. Go dependencies? Image scanning? Once you configure it how do you modify the config? For instance if we add a new repo. Would also be nice to get a demo of how this works in a WG meeting so we can proliferate this out to the community.

**Comment by bnevis-i** [comment]
According to Pranab Bajpai <pbajpai@linuxfoundation.org> we are already enrolled at https://security.lfx.linuxfoundation.org/#/a2bfb3f1-9c3d-4a39-beb6-ae102c4ccbca/overview

Can close this ticket.

**Comment by bnevis-i** [comment]
@ernestojeda Can you close this ticket?
