### ISSUE TITLE
Integrate the snap release into the release kraken in cd-management

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/cd-management#3]
Implement edgeXSnapRelease that will release the already staged snaps using edgeXSnap.

**Comment by jamesrgregg** [comment]
[US6246](https://rally1.rallydev.com/#/detail/userstory/b4d88b37-8986-4e63-92a9-30c5310e3df7?fdp=true): EdgeX DevOps: Integrate the snap release into the release kraken in cd-management
