### ISSUE TITLE
Milestone synchronization doesn't work as expected

### ISSUE THREAD

**Issue by soda480** [edgexfoundry/cd-management#33]
The milestone synchronization didn't work as expected. In investigating the issue; several of the target repos already had a milestone called 'EdgeX Hanoi' which is a different name and more importantly a **different milestone number** than what the source repo has defined in cd-management. The GitHub API only supports getting and updating a milestone by its milestone number, for milestones GitHub uses the milestone number as the resource identifier.

https://developer.github.com/v3/issues/milestones/#get-a-milestone
https://developer.github.com/v3/issues/milestones/#update-a-milestone

Thus synchronization of milestones is going to require a bit more logic since some of the repos already have milestones created with the same milestone number but for a different title than what the source repo has defined. 

For example, in cd-management Hanoi is defined as milestone/1 but some repos already have milestone/1 assigned to something else (Geneva, Edinburg, etc.), and other repos already have a Hanoi milestone but it is called 'EdgeX Hanoi'.  It appears that milestone tiles are case sensitive as well thus the following are considered two distinct milestones:  Hanoi and hanoi. 

We need to standardize on what the milestone name should be and set it in cd-management appropriately. Then update the synchronization to synchronize milestones by title and not by milestone number.

**Comment by jamesrgregg** [comment]
[US6772](https://rally1.rallydev.com/#/detail/userstory/395991220040?fdp=true): EdgeX DevOps: Milestone synchronization doesn't work as expected
