### ISSUE TITLE
EdgeX DevOps: Add Swaggerhub global function to EdgeX release kraken

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/cd-management#38]
Integrate the swagger hub release function into the EdgeX release-kraken pipeline.

[US6234](https://rally1.rallydev.com/#/detail/userstory/372728101624?fdp=true): EdgeX DevOps: Add Swaggerhub global function to EdgeX release kraken

**Comment by ernestojeda** [comment]
This has been implemented inline in the following pipelines and will no longer be part of the the EdgeX release kraken build.

- [x] edgexBuildGoApp
- [x] edgexBuildGoParallel

**Comment by jamesrgregg** [comment]
Developed the library and and implemented it into the new edgeXBuildGoParallel and edgeXBuildGoApp
