### ISSUE TITLE
EdgeX DevOps: resolve failure with git semver tag force capability

### ISSUE THREAD

**Issue by soda480** [edgexfoundry/cd-management#55]
understand why the following job failed when forcing tag:

https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fcd-management/detail/release/26/pipeline

**Comment by soda480** [comment]
I believe this is happening because `edgeXSemver` ignores command if GITSEMVER_HEAD_TAG is set:
https://github.com/edgexfoundry/edgex-global-pipelines/blob/master/vars/edgeXSemver.groovy#L47

**Comment by jamesrgregg** [comment]
in order of priority.. we decided internally that this one needs to be fixed but not highest priority.
