### ISSUE TITLE
Refactor *-github-* Python scripts to use github3api module

### ISSUE THREAD

**Issue by soda480** [edgexfoundry/cd-management#87]
To keep Python scripts DRY and to practice good reuse techniques - refactor the sync-github-labels, prune-github-tags and create-github-release scripts in order to consume the github3api module for consuming the GitHub API.

**Comment by jamesrgregg** [comment]
[US7331](https://rally1.rallydev.com/#/detail/userstory/440101159624?fdp=true): EdgeX DevOps: Spike: Research best way to scan docker images pre release

**Comment by jamesrgregg** [comment]
Closed in Sprint 61
